name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# permissions:
#  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      YOUTUBE_API_KEY: ${{secrets.YOUTUBE_API_KEY}}

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Test on PHP 7.0
      uses: php-actions/phpunit@v3
      with:
        # configuration: ./phpunit.xml
        php_version: "7.0"

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

#    - name: Run test suite
#      run: ./vendor/bin/phpunit
